apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mastodon
  namespace: default
spec:
  interval: 5m
  ref:
    branch: main
  url: https://github.com/mastodon/chart
  ignore: |
    /*
    !/Chart.yaml
    !/values.yaml
    !/templates/
