apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: mastodon
  namespace: default
spec:
  interval: 5m
  url: https://github.com/mastodon/chart
  ignore: |
    exclude /dev*/
